### ISSUE TITLE
AttributeError when generate overview images

### ISSUE THREAD

**Issue by Yannan-Chen** [galizia-lab/pyview#27]
After pressing 'Generate(new)', following error popped up. I guess it's related to the PyQt5 backend.

```
Traceback (most recent call last):
  File "/Users/yannanchen/anaconda3/envs/viewPy0/lib/python3.10/site-packages/view/gui/central_widget.py", line 809, in generate_overview
    pop_show_overview(flags=self.flags, p1=self.get_selected_data_p1(),
  File "/Users/yannanchen/anaconda3/envs/viewPy0/lib/python3.10/site-packages/view/python_core/overviews/__init__.py", line 333, in pop_show_overview
    label2use = dedupilicate(value=label, existing_values=get_current_pyplot_window_titles())
  File "/Users/yannanchen/anaconda3/envs/viewPy0/lib/python3.10/site-packages/view/python_core/overviews/__init__.py", line 258, in get_current_pyplot_window_titles
    titles.append(fig.canvas.get_window_title())
AttributeError: 'FigureCanvasQTAgg' object has no attribute 'get_window_title'
```

**Comment by ajkswamy** [comment]
closed by #33
